### ISSUE TITLE
Preferred single node setup

### ISSUE THREAD

**Issue by rmkraus** [NVIDIA/cloud-native-core#19]
This may not actually be a bug as it is a question more for guidance. 

We are running a single node EGX "cluster". It seems that by default, in this configuration, the single node will only have the "master" label and not the "worker" label. 

When only running single node, is the suggested solution to simply add the worker label to the node manually?

**Comment by angudadevops** [comment]
Agree but we tainted the the master node to run the workloads. so we can change until unless workloads are expected to run based on node role but we for EGX stack we didn't see that scenario. If you need that label for master can add that too.

**Comment by angudadevops** [comment]
@rmkraus hope that answer your question
