### ISSUE TITLE
calico.yaml url has expired

### ISSUE THREAD

**Issue by BharathReddy294** [NVIDIA/cloud-native-core#27]
The URL in the following command 
kubectl apply -f https://docs.projectcalico.org/v3.23/manifests/calico.yaml of document: https://github.com/NVIDIA/cloud-native-core/blob/master/install-guides/Ubuntu_Server_v7.0.md has expired.

Using the following URL resolved my issue:
https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/calico.yaml

**Comment by mattf** [comment]
cc @erikbohnhorst

this is also an issue for the playbooks

**Comment by francisguillier** [comment]
the issue was fixed (by @angudadevops) in both the step by step guide and in the Ansible playbook.

kubectl apply -f https://projectcalico.docs.tigera.io/archive/v3.23/manifests/calico.yaml is the new link we use.

**Comment by angudadevops** [comment]
issue fixed with latest versions
